{{- if .Values.registrar.enabled -}}
{{- $global := deepCopy .Values.global.ingress }}
{{- $common := deepCopy .Values.common.ingress }}
{{- $registrar := deepCopy .Values.registrar.ingress }}
{{- $ingress := mergeOverwrite $global $common $registrar }}
{{- $defaultHost := printf "%s.%s" (tpl $ingress.subdomain .) $ingress.baseDomain }}
{{- $ingressTLSRequired := and $ingress.tls.enabled (not $ingress.tls.terminatedAtProxy) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "zenith.componentname" (list . "registrar") }}
  labels: {{ include "zenith.componentLabels" (list . "registrar") | nindent 4 }}
  {{- $tlsAnnotations := $ingressTLSRequired | ternary $ingress.tls.annotations dict }}
  {{- $annotations := mergeOverwrite $ingress.annotations $tlsAnnotations }}
  {{- with $annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if $ingressTLSRequired }}
  tls:
    - hosts:
        - {{ default $defaultHost $ingress.host | quote }}
      {{- $defaultSecretName := printf "%s-tls" (include "zenith.componentname" (list . "registrar")) }}
      secretName: {{ default $defaultSecretName $ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ default $defaultHost $ingress.host | quote }}
      http:
        paths:
          # Only the associate endpoint is made available through ingress
          - path: /associate
            pathType: Prefix
            backend:
              service:
                name: {{ include "zenith.componentname" (list . "registrar") }}
                port:
                  name: http
{{- end }}
